### 3.1 a) Montrer que les matrices de réflexion $Q_i$ sont orthogonales

#### 1. Orthogonalité d’une matrice de Householder

Une matrice de Householder est définie par :

$$
H = I - 2\frac{v v^T}{v^T v},
$$

où $v \neq 0$.  
On veut démontrer que :

$$
H^T H = I.
$$

Comme $v v^T$ est symétrique :

$$
(v v^T)^T = v v^T,
$$
Deux matrices, une colonne et l'autre ligne de même longueure et identique, donnera le même résultats malgré la transposée.

Donc :

$$
H^T = H.
$$

Ainsi :

$$
H^T H = H^2.
$$

Calculons $H^2$ :

$$
H^2
= \left(I - 2\frac{v v^T}{v^T v}\right)^2
= I - 4\frac{v v^T}{v^T v}
  + 4\frac{v v^T v v^T}{(v^T v)^2}.
$$

Nous savons que :

$$
v v^T v = (v^T v) v,
$$

donc :

$$
v v^T v v^T = (v^T v) v v^T.
$$

Ainsi :

$$
4\frac{v v^T v v^T}{(v^T v)^2}
= 4\frac{(v^T v) v v^T}{(v^T v)^2}
= 4\frac{v v^T}{v^T v}.
$$

En substituant :

$$
H^2
= I - 4\frac{v v^T}{v^T v}
  + 4\frac{v v^T}{v^T v}
= I.
$$

Donc :

$$
H^T H = I,
$$

ce qui montre que toute matrice de Householder est orthogonale.

---

#### 2. Orthogonalité des matrices $Q_i$ ####

Les matrices $Q_i$ sont définies par blocs :

$$
Q_i =
\begin{pmatrix}
I_i & 0 \\
0 & H_{m,i}
\end{pmatrix}.
$$

La transposée est :

$$
Q_i^T =
\begin{pmatrix}
I_i & 0 \\
0 & H_{m,i}^T
\end{pmatrix}
=
\begin{pmatrix}
I_i & 0 \\
0 & H_{m,i}
\end{pmatrix},
$$

puisque $I_i$  et  $H_{m,i}$ sont symétriques.

Alors :

$$
Q_i^T Q_i =
\begin{pmatrix}
I_i & 0 \\
0 & H_{m,i}
\end{pmatrix}
\begin{pmatrix}
I_i & 0 \\
0 & H_{m,i}
\end{pmatrix}
=
\begin{pmatrix}
I_i & 0 \\
0 & H_{m,i}H_{m,i}
\end{pmatrix}.
$$

Comme $H_{m,i}$ est orthogonale :

$$
H_{m,i}H_{m,i} = I_{m-i}.
$$

Donc :

$$
Q_i^T Q_i = I_m.
$$

Ainsi, chaque matrice $Q_i$ est orthogonale.

### 3.1 b) Démontrer l’équation (3.5) et que la matrice $Q$ est orthogonale

On applique successivement les matrices $Q_i$ à la matrice $A$ :

$$
Q_{n-1} Q_{n-2} \cdots Q_1 Q_0 A = R,
$$

où $R$ est triangulaire supérieure.

On multiplie à gauche par la transposée du produit :

$$
(Q_{n-1} Q_{n-2} \cdots Q_0)^T.
$$

Comme chaque $Q_i$ est orthogonale :

$$
Q_i^T = Q_i^{-1}.
$$

On obtient :

$$
A = Q_0^T Q_1^T \cdots Q_{n-2}^T Q_{n-1}^T R.
$$

On définit alors :

$$
Q = Q_0^T Q_1^T \cdots Q_{n-1}^T.
$$

Ce qui donne :

$$
A = QR.
$$

C’est exactement l’équation (3.5) de l’énoncé.

---

### Orthogonalité de $Q$
Comme chaque $Q_i$ est orthogonale, chaque $Q_i^T$ l’est aussi.

Le produit de matrices orthogonales est orthogonale.

Ainsi :

$$
Q^T Q = 
(Q_{n-1} \cdots Q_1 Q_0)
(Q_0^T Q_1^T \cdots Q_{n-1}^T)
= I.
$$

Donc, la matrice $Q$ de la décomposition QR est orthogonale.


#### Question 3.1 c ####

In [ ]:
import numpy as np

def householder_qr(A):
    """Calcule la décomposition QR d’une matrice A en utilisant les réflexions de Householder. """
    
    m, n = A.shape  # donne les valeurs correspondantes à m et n de la matrice A
    Q = np.eye(m)   # Crée une matrice identité de taille m x m pour stocker les transformations de Householder
    R = A.copy()    # Crée une copie de la matrice A pour stocker les résultats de la décomposition

    for k in range(n):  # on passe au travers de chaque colonne de la matrice A

        # Extract the column vector to be transformed
        x = R[k:, k]  # vecteur colonne tronqué à partir de la ligne k et de la colonne k

        # Compute the Householder vector
        e = np.zeros_like(x)  # Crée un vecteur de même taille que x, rempli de zéros
        sign = 1 if x[0] >= 0 else -1  # Choisit le signe pour éviter les problèmes de cancellation numérique
        e[0] = sign * np.linalg.norm(x)  # Met la norme de x dans la première composante du vecteur e

        u = x + e  # Calcule le vecteur de Householder selon la définition du TP (x + sign*||x||*e1)
        beta = u @ u  # Calcule u^T u (un scalaire), utilisé dans la formule de Householder

        if beta == 0:  # Cas dégénéré : aucune transformation nécessaire
            continue

        # Create the Householder matrix
        H_k = np.eye(m)  # Matrice identité m x m
        H_k[k:, k:] -= 2 * np.outer(u, u) / beta  # Applique la formule H = I - 2 uu^T / (u^T u)

        # Apply the transformation to R and accumulate Q
        R = H_k @ R  # Applique la réflexion à R pour annuler les éléments sous la diagonale
        Q = Q @ H_k  # Accumule les transformations pour construire la matrice Q finale

    return Q, R

# Example usage
if __name__ == "__main__":    
    A = np.array([[4, 1], [2, 3], [1, 2]], dtype=float)
    Q, R = householder_qr(A)    
    print("Q:\n", Q)    
    print("R:\n", R)
    # Verify that A = Q @ R
    print("Q @ R:\n", Q @ R)
    print("A:\n", A)
    print("Verification (Q @ R == A):", np.allclose(Q @ R, A))

Q:
 [[-0.87287156  0.48107024  0.08164966]
 [-0.43643578 -0.69487923 -0.57154761]
 [-0.21821789 -0.53452248  0.81649658]]
R:
 [[-4.58257569e+00 -2.61861468e+00]
 [ 4.39110249e-16 -2.67261242e+00]
 [ 4.62000826e-17 -1.30304986e-16]]
Q @ R:
 [[4. 1.]
 [2. 3.]
 [1. 2.]]
A:
 [[4. 1.]
 [2. 3.]
 [1. 2.]]
Verification (Q @ R == A): True
